version: '2'

services:

  satellite:
    image: docker-registry.beta.browxy.com/browxy_satellite:latest
    env_file:
      - env.prod
    container_name: satellite
    hostname: satellite
    networks:
      - browxy
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /srv/satellite_data:/var/satellite
    ulimits:
      nproc: 524288
      nofile: 524288

networks:
  browxy:
    external: true


